### ISSUE TITLE
F+

### ISSUE THREAD

**Issue by YoDobchev** [JerryPopi/F-#1]
![E1fkyqZVIAACwvd](https://user-images.githubusercontent.com/16627162/122256328-9fd8ad00-ced7-11eb-8beb-2bae5489340d.jpg)
-iskam da contributiram

**Comment by JerryPopi** [comment]
napravi pull request s featuri i she vidim.

**Comment by YoDobchev** [comment]
![IMG_5968](https://user-images.githubusercontent.com/16627162/122276279-4ed3b380-ceed-11eb-9073-879451533324.JPG)

**Comment by JerryPopi** [comment]
Seks
